version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling
      - touch .env
      - echo "APP_HOST=127.0.0.1" >> .env
      - echo "APP_PORT=8000" >> .env
      - echo "ACCESS_TOKEN_DURATION=$ACCESS_TOKEN_DURATION" >> .env
      - echo "ACCESS_TOKEN_SECRET_KEY=$ACCESS_TOKEN_SECRET_KEY" >> .env
      - echo "API_URL=$API_URL" >> .env
      - echo "AWS_REGION=$AWS_REGION" >> .env
      - echo "AWS_ACCESS_KEY=$AWS_ACCESS_KEY" >> .env
      - echo "AWS_SECRET_KEY=$AWS_SECRET_KEY" >> .env
      - echo "DB_CLIENT=$DB_CLIENT" >> .env
      - echo "DB_HOST=$DB_HOST" >> .env
      - echo "DB_PORT=$DB_PORT" >> .env
      - echo "DB_NAME=$DB_NAME" >> .env
      - echo "DB_USER=$DB_USER" >> .env
      - echo "DB_PASS=$DB_PASS" >> .env
      - echo "FACEBOOK_CLIENT_ID=$FACEBOOK_CLIENT_ID" >> .env
      - echo "FACEBOOK_CLIENT_SECRET=$FACEBOOK_CLIENT_SECRET" >> .env
      - echo "GAMES_URL=$GAMES_URL" >> .env
      - echo "GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID" >> .env
      - echo "GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET" >> .env
      - echo "REFRESH_TOKEN_DURATION=$REFRESH_TOKEN_DURATION" >> .env
      - echo "REFRESH_TOKEN_SECRET_KEY=$REFRESH_TOKEN_SECRET_KEY" >> .env
      - echo "SENTRY_DSN=$SENTRY_DSN" >> .env
      - echo "SENTRY_TRACE_SAMPLE_RATE=$SENTRY_TRACE_SAMPLE_RATE" >> .env
      - echo "SES_EMAIL=$SES_EMAIL" >> .env
      - echo "SES_FROM =$SES_FROM" >> .env
      - echo "STATIC_URL=$STATIC_URL" >> .env
      - echo "STAGE=$STAGE" >> .env
      - echo "APPLE_BUNDLE_ID=$APPLE_BUNDLE_ID" >> .env
      - echo "FCM_SERVER_KEY=$FCM_SERVER_KEY" >> .env
      - echo "CRON_AUTHORIZATION_TOKEN=$CRON_AUTHORIZATION_TOKEN" >> .env
      - echo "MAILJET_API_KEY=$MAILJET_API_KEY" >> .env
      - echo "MAILJET_SECRET_KEY=$MAILJET_SECRET_KEY" >> .env
  post_build:
    commands:
      - echo Build completed on `date`
      - chmod u+x -R scripts
# Include only the files required for your application to run.
artifacts:
  files:
    - "**/*"
